using System.Collections.Generic;

namespace StacklandsRandomizerNS.IdeaMap
{
    public class Ideas
    {
        public static Dictionary<string, List<string>> allIdeas = new(){
            {"Cooking Devices", new List<string> {"campfire", "hotpot", "stove"}},
            {"Foodstuffs", new List<string> {"cookedmeat", "frittata", "fruitsalad", "milkshake", "omelette", "stew"}},
            {"Animal Pen", new List<string> {"animalpen"}},
            {"Axe", new List<string> {"axe"}},
            {"Bone Spear", new List<string> {"bone_spear"}},
            {"Boomerang", new List<string> {"boomerang"}},
            {"Breeding Pen", new List<string> {"breedingpen"}},
            {"Brick", new List<string> {"brick"}},
            {"Brickyard", new List<string> {"brickyard"}},
            {"Butchery", new List<string> {"slaughterhouse"}},
            {"Chainmail Armor", new List<string> {"chainmail_armor"}},
            {"Chicken", new List<string> {"chicken"}},
            {"Club", new List<string> {"club"}},
            {"Coin Chest", new List<string> {"coinchest"}},
            {"Crane", new List<string> {"conveyor"}},
            {"Dustbin", new List<string> {"trash_can"}},
            {"Farm", new List<string> {"farm"}},
            {"Garden", new List<string> {"garden"}},
            {"Growth", new List<string> {"growth"}},
            {"Hammer", new List<string> {"hammer"}},
            {"House", new List<string> {"house"}},
            {"Iron Bar", new List<string> {"iron_bar"}},
            {"Iron Mine", new List<string> {"mine"}},
            {"Iron Shield", new List<string> {"iron_shield"}},
            {"Lumber Camp", new List<string> {"lumbercamp"}},
            {"Magic Blade", new List<string> {"magic_blade"}},
            {"Magic Glue", new List<string> {"heavy_foundation"}},
            {"Magic Ring", new List<string> {"magic_ring"}},
            {"Magic Staff", new List<string> {"magic_staff"}},
            {"Magic Tome", new List<string> {"magic_tome"}},
            {"Magic Wand", new List<string> {"magic_wand"}},
            {"Market", new List<string> {"market"}},
            {"Offspring", new List<string> {"offspring"}},
            {"Pickaxe", new List<string> {"pickaxe"}},
            {"Plank", new List<string> {"planks"}},
            {"Quarry", new List<string> {"quarry"}},
            {"Resource Chest", new List<string> {"resourcechest"}},
            {"Resource Magnet", new List<string> {"resource_magnet"}},
            {"Sawmill", new List<string> {"sawmill"}},
            {"Shed", new List<string> {"shed"}},
            {"Slingshot", new List<string> {"slingshot"}},
            {"Smelter", new List<string> {"smelting"}},
            {"Smithy", new List<string> {"smithy"}},
            {"Spear", new List<string> {"woodenweapons"}},
            {"Spiked Plank", new List<string> {"spiked_plank"}},
            {"Stick", new List<string> {"carving"}},
            {"Sword", new List<string> {"ironweapons"}},
            {"Temple", new List<string> {"temple"}},
            {"Throwing Stars", new List<string> {"throwing_star"}},
            {"University", new List<string> {"university"}},
            {"Warehouse", new List<string> {"warehouse"}},
            {"Wizard Robe", new List<string> {"wizard_robe"}},
            {"Wooden Shield", new List<string> {"wooden_shield"}}
        };
    }
}